export type Product = {
  id: string
  name: string
  category: string
  price: number
  image: string
  description: string
  badge?: 'Terlaris' | 'Baru' | 'Promo'
}

export const products: Product[] = [
  {
    id: 'royal-canin-adult-dog-10kg',
    name: 'Royal Canin Adult Dog 10kg',
    category: 'Anjing',
    price: 285000,
    image: 'https://source.unsplash.com/600x600/?dog+food',
    description: 'Makanan premium untuk anjing dewasa dengan nutrisi seimbang untuk energi harian.',
    badge: 'Terlaris',
  },
  {
    id: 'pedigree-puppy-chicken-8kg',
    name: 'Pedigree Puppy Chicken 8kg',
    category: 'Anjing',
    price: 195000,
    image: 'https://source.unsplash.com/600x600/?dog+food+bowl',
    description: 'Makanan anak anjing rasa ayam untuk mendukung pertumbuhan tulang dan otot.',
    badge: 'Promo',
  },
  {
    id: 'whiskas-tuna-pouch-85gr',
    name: 'Whiskas Tuna Pouch 85gr',
    category: 'Kucing',
    price: 12000,
    image: 'https://source.unsplash.com/600x600/?cat+food',
    description: 'Makanan basah kucing rasa tuna dengan tekstur lembut dan aroma menggoda.',
    badge: 'Terlaris',
  },
  {
    id: 'friskies-kitten-15kg',
    name: 'Friskies Kitten 1.5kg',
    category: 'Kucing',
    price: 65000,
    image: 'https://source.unsplash.com/600x600/?kitten+eating',
    description: 'Makanan kering untuk kitten dengan nutrisi lengkap untuk masa tumbuh aktif.',
    badge: 'Baru',
  },
  {
    id: 'drools-adult-cat-salmon-3kg',
    name: 'Drools Adult Cat Salmon 3kg',
    category: 'Kucing',
    price: 145000,
    image: 'https://source.unsplash.com/600x600/?cat+salmon',
    description: 'Makanan kucing dewasa rasa salmon dengan protein tinggi dan omega untuk bulu sehat.',
    badge: 'Terlaris',
  },
  {
    id: 'royal-canin-persian-2kg',
    name: 'Royal Canin Persian 2kg',
    category: 'Kucing',
    price: 225000,
    image: 'https://source.unsplash.com/600x600/?persian+cat',
    description: 'Formula khusus kucing Persia untuk kesehatan kulit, bulu, dan pencernaan.',
    badge: 'Terlaris',
  },
  {
    id: 'kalung-gps-anjing',
    name: 'Kalung GPS Anjing',
    category: 'Anjing',
    price: 320000,
    image: 'https://source.unsplash.com/600x600/?dog+collar',
    description: 'Kalung GPS modern untuk membantu memantau aktivitas dan posisi anjing kesayangan.',
    badge: 'Baru',
  },
  {
    id: 'tali-leash-kulit-premium',
    name: 'Tali Leash Kulit Premium',
    category: 'Anjing',
    price: 185000,
    image: 'https://source.unsplash.com/600x600/?dog+leash',
    description: 'Tali leash kulit premium yang kuat, nyaman digenggam, dan tampil elegan.',
  },
  {
    id: 'kandang-lipat-besi-m',
    name: 'Kandang Lipat Besi M',
    category: 'Anjing',
    price: 450000,
    image: 'https://source.unsplash.com/600x600/?dog+cage',
    description: 'Kandang lipat besi ukuran M, praktis untuk rumah maupun perjalanan.',
  },
  {
    id: 'kandang-kucing-tingkat-3',
    name: 'Kandang Kucing Tingkat 3',
    category: 'Kucing',
    price: 875000,
    image: 'https://source.unsplash.com/600x600/?cat+cage',
    description: 'Kandang tingkat tiga untuk kucing aktif dengan ruang bermain dan istirahat luas.',
    badge: 'Promo',
  },
  {
    id: 'tempat-tidur-bulu-bulat',
    name: 'Tempat Tidur Bulu Bulat',
    category: 'Kucing',
    price: 135000,
    image: 'https://source.unsplash.com/600x600/?cat+bed',
    description: 'Tempat tidur bulu lembut berbentuk bulat untuk tidur kucing yang lebih nyaman.',
  },
  {
    id: 'mainan-bola-interaktif-kucing',
    name: 'Mainan Bola Interaktif Kucing',
    category: 'Kucing',
    price: 75000,
    image: 'https://source.unsplash.com/600x600/?cat+toy+ball',
    description: 'Mainan bola interaktif untuk menstimulasi insting berburu dan aktivitas harian kucing.',
  },
  {
    id: 'sisir-grooming-bulu-halus',
    name: 'Sisir Grooming Bulu Halus',
    category: 'Grooming',
    price: 55000,
    image: 'https://source.unsplash.com/600x600/?pet+grooming',
    description: 'Sisir grooming lembut untuk merapikan bulu halus tanpa membuat kulit iritasi.',
  },
  {
    id: 'shampo-anjing-anti-kutu',
    name: 'Shampo Anjing Anti Kutu',
    category: 'Grooming',
    price: 85000,
    image: 'https://source.unsplash.com/600x600/?dog+shampoo',
    description: 'Shampo anjing dengan formula anti kutu dan aroma segar untuk perawatan rutin.',
    badge: 'Terlaris',
  },
  {
    id: 'trimmer-bulu-hewan-elektrik',
    name: 'Trimmer Bulu Hewan Elektrik',
    category: 'Grooming',
    price: 275000,
    image: 'https://source.unsplash.com/600x600/?pet+trimmer',
    description: 'Trimmer elektrik untuk merapikan bulu hewan peliharaan dengan mudah di rumah.',
  },
  {
    id: 'parfum-anjing-lavender',
    name: 'Parfum Anjing Lavender',
    category: 'Grooming',
    price: 65000,
    image: 'https://source.unsplash.com/600x600/?dog+spray',
    description: 'Parfum anjing aroma lavender yang lembut dan tahan lama setelah grooming.',
  },
  {
    id: 'aquarium-set-40cm',
    name: 'Aquarium Set 40cm',
    category: 'Ikan',
    price: 350000,
    image: 'https://source.unsplash.com/600x600/?aquarium+fish',
    description: 'Paket aquarium 40cm untuk pemula, cocok untuk ikan hias kecil di rumah.',
    badge: 'Baru',
  },
  {
    id: 'filter-aquarium-internal',
    name: 'Filter Aquarium Internal',
    category: 'Ikan',
    price: 125000,
    image: 'https://source.unsplash.com/600x600/?aquarium+filter',
    description: 'Filter internal untuk menjaga air aquarium tetap bersih dan sirkulasi stabil.',
  },
  {
    id: 'pakan-ikan-mas-hikari',
    name: 'Pakan Ikan Mas Hikari',
    category: 'Ikan',
    price: 45000,
    image: 'https://source.unsplash.com/600x600/?fish+food',
    description: 'Pakan ikan mas berkualitas untuk warna cerah dan pertumbuhan sehat.',
  },
  {
    id: 'dekorasi-aquarium-batu',
    name: 'Dekorasi Aquarium Batu',
    category: 'Ikan',
    price: 55000,
    image: 'https://source.unsplash.com/600x600/?aquarium+decoration',
    description: 'Dekorasi batu aquarium untuk tampilan natural dan tempat eksplorasi ikan.',
  },
  {
    id: 'sangkar-burung-bambu',
    name: 'Sangkar Burung Bambu',
    category: 'Burung',
    price: 175000,
    image: 'https://source.unsplash.com/600x600/?bird+cage+bamboo',
    description: 'Sangkar burung bambu dengan desain klasik, ringan, dan nyaman untuk burung kecil.',
  },
  {
    id: 'pakan-burung-kenari',
    name: 'Pakan Burung Kenari',
    category: 'Burung',
    price: 35000,
    image: 'https://source.unsplash.com/600x600/?bird+seeds',
    description: 'Campuran biji pilihan untuk mendukung stamina dan kicauan burung kenari.',
  },
  {
    id: 'mainan-gantung-burung',
    name: 'Mainan Gantung Burung',
    category: 'Burung',
    price: 45000,
    image: 'https://source.unsplash.com/600x600/?bird+toy',
    description: 'Mainan gantung warna-warni untuk menjaga burung tetap aktif dan tidak mudah stres.',
  },
  {
    id: 'vitamin-c-anjing',
    name: 'Vitamin C Anjing',
    category: 'Obat',
    price: 95000,
    image: 'https://source.unsplash.com/600x600/?dog+vitamin',
    description: 'Suplemen vitamin C untuk membantu daya tahan tubuh anjing tetap prima.',
  },
  {
    id: 'obat-cacing-kucing',
    name: 'Obat Cacing Kucing',
    category: 'Obat',
    price: 55000,
    image: 'https://source.unsplash.com/600x600/?cat+medicine',
    description: 'Obat cacing kucing untuk perawatan kesehatan berkala sesuai anjuran pemakaian.',
  },
  {
    id: 'spot-on-anti-kutu-kucing',
    name: 'Spot On Anti Kutu Kucing',
    category: 'Obat',
    price: 125000,
    image: 'https://source.unsplash.com/600x600/?cat+flea+treatment',
    description: 'Perawatan spot on untuk membantu melindungi kucing dari kutu dan parasit luar.',
    badge: 'Terlaris',
  },
  {
    id: 'susu-bayi-kucing',
    name: 'Susu Bayi Kucing',
    category: 'Kucing',
    price: 75000,
    image: 'https://source.unsplash.com/600x600/?kitten+milk',
    description: 'Susu formula untuk bayi kucing sebagai dukungan nutrisi saat masa pertumbuhan awal.',
  },
  {
    id: 'bowl-makan-stainless-double',
    name: 'Bowl Makan Stainless Double',
    category: 'Aksesoris',
    price: 95000,
    image: 'https://source.unsplash.com/600x600/?dog+bowl+stainless',
    description: 'Bowl makan stainless double yang higienis, stabil, dan mudah dibersihkan.',
  },
  {
    id: 'baju-anjing-hoodie-s',
    name: 'Baju Anjing Hoodie S',
    category: 'Anjing',
    price: 145000,
    image: 'https://source.unsplash.com/600x600/?dog+clothing',
    description: 'Hoodie ukuran S untuk anjing kecil, nyaman dipakai dan tampil menggemaskan.',
  },
  {
    id: 'carrier-tas-kucing-oxford',
    name: 'Carrier Tas Kucing Oxford',
    category: 'Kucing',
    price: 285000,
    image: 'https://source.unsplash.com/600x600/?cat+carrier+bag',
    description: 'Tas carrier bahan oxford untuk membawa kucing bepergian dengan aman dan nyaman.',
    badge: 'Promo',
  },
  {
    id: 'scratch-post-kucing',
    name: 'Scratch Post Kucing',
    category: 'Kucing',
    price: 215000,
    image: 'https://source.unsplash.com/600x600/?cat+scratch+post',
    description: 'Scratch post kokoh untuk menyalurkan kebiasaan menggaruk dan melindungi furnitur.',
  },
  {
    id: 'litter-box-tertutup',
    name: 'Litter Box Tertutup',
    category: 'Kucing',
    price: 195000,
    image: 'https://source.unsplash.com/600x600/?cat+litter+box',
    description: 'Litter box tertutup untuk menjaga area rumah lebih rapi dan mengurangi bau.',
  },
  {
    id: 'pasir-kucing-wangi-10l',
    name: 'Pasir Kucing Wangi 10L',
    category: 'Kucing',
    price: 85000,
    image: 'https://source.unsplash.com/600x600/?cat+litter+sand',
    description: 'Pasir kucing wangi 10L dengan daya serap baik dan mudah menggumpal.',
  },
  {
    id: 'topi-anjing-lucu',
    name: 'Topi Anjing Lucu',
    category: 'Anjing',
    price: 65000,
    image: 'https://source.unsplash.com/600x600/?dog+hat+cute',
    description: 'Topi lucu untuk anjing kecil, cocok untuk foto, event, atau hadiah.',
  },
  {
    id: 'snack-treat-anjing-jerky',
    name: 'Snack Treat Anjing Jerky',
    category: 'Anjing',
    price: 55000,
    image: 'https://source.unsplash.com/600x600/?dog+treats',
    description: 'Snack jerky untuk reward latihan atau camilan sehat di sela aktivitas.',
  },
]

export const productCategories = [
  'Semua',
  'Anjing',
  'Kucing',
  'Burung',
  'Ikan',
  'Grooming',
  'Aksesoris',
  'Obat',
]

export function formatRupiah(value: number) {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
  }).format(value)
}

export function getProductsByCategory(category: string) {
  if (category === 'Semua') return products
  return products.filter((product) => product.category.toLowerCase() === decodeURIComponent(category).toLowerCase())
}

export function getFeaturedProducts() {
  return products.filter((product) => product.badge === 'Terlaris').slice(0, 6)
}
